BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Category";
CREATE TABLE "Category" (
"Id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
"Name" TEXT NOT NULL DEFAULT NULL);
COMMIT;

BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Comparison";
CREATE TABLE "Comparison" (
"Id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
"UnitTypeId" INTEGER REFERENCES UnitType(Id) ON DELETE NO ACTION,
"UnitId" INTEGER REFERENCES UnitType(Id) ON DELETE NO ACTION,
"CategoryId" INTEGER REFERENCES Category(Id) ON DELETE NO ACTION DEFAULT NULL,
"Name" TEXT DEFAULT NULL,
"CheapestComparableId" DEFAULT NULL);
COMMIT;

BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Comparable";
CREATE TABLE "Comparable" (
"Id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
"ComparisonId" INTEGER REFERENCES Comparison(id) ON DELETE CASCADE NULL,
"UnitId" INTEGER REFERENCES Unit(id) ON DELETE NO ACTION NOT NULL,
"Store" TEXT DEFAULT NULL,
"Product" TEXT DEFAULT NULL,
"Price" REAL NOT NULL DEFAULT 0,
"Quantity" REAL NOT NULL DEFAULT 0,
"ModifiedOn" TEXT NOT NULL);
COMMIT;


BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Meta";
CREATE TABLE "Meta" (
"DbVersion" REAL DEFAULT NULL);
COMMIT;

insert into Meta (DbVersion) values (1);